### ISSUE TITLE
LTI 1.1 & 1.3 connections should resolve to the same course

### ISSUE THREAD

**Issue by perllaghu** [maths/enrol_lticoursetemplate#10]
The plugin supports both LTI 1.1 & 1.3 [Advantage] connections - and they work.

For a given course in the Providers' VLE, both LTI 1.1 and 1.3 connections should reach the same course in Moodle.

**Comment by ajuszczyk** [comment]
The LTI 1.1 uses "consumer key" and the LTI 1.3 uses "platform" custom parameter to create and check for courses and users. If the plugin gets updated to the LTI 1.3 version the "platform" custom parameter has to be set the same as the "consumer key" value in the VLE (Learn, Moodle, Canvas...) for the new connection to recognise existing users and courses.
Attached examples in the Learn VLE.
LTI 1.1:
![Screenshot 2023-06-27 at 09 51 44](https://github.com/maths/enrol_lticoursetemplate/assets/2144020/29b80fde-3a75-4a32-8570-c76764bbf7d8)

LTI 1.3:
![Screenshot 2023-06-27 at 09 54 26](https://github.com/maths/enrol_lticoursetemplate/assets/2144020/1a2cce3f-c138-404b-8121-f60a689a778a)
