### ISSUE TITLE
Cannot update existing moodle to use `Update-to-use-LTI-Advantage` branch

### ISSUE THREAD

**Issue by perllaghu** [maths/enrol_lticoursetemplate#4]
Running moodle 4.0.3 in a docker instance [in a kubernetes cluster], with an external [postgresql] database, and `moodledata` as a mounted volume, and `v1.1` of the code - redeploying an image with the `Update-to-use-LTI-Advantage` branch code [all other components unchanged] fails to upgrade with the error `"enrol_ct_tools" does not exist` and a `dbtablenotexist` error.

Note that deploying an image with moodle 4.1.3 and the `Update-to-use-LTI-Advantage` branch into the cluster with an empty database & no moodledata contents installs fine.... but this is a _blank_ install, and not appropriate for an existing service

**Comment by agxs** [comment]
Is this perhaps an issue with the `prefix` parameter in the moodle `config.php`?

Eg, `$CFG->prefix    = 'mdl_';` is set in our config so the actual table name is `mdl_enrol_ct_tools`

**Comment by perllaghu** [comment]
Confirm this PR allows service to update without having to clear data.

Need to test whether connections created under the old system continue to work with the new plugin
