### ISSUE TITLE
Cannot delete deployment, and thus registered platform

### ISSUE THREAD

**Issue by perllaghu** [maths/enrol_lticoursetemplate#6]
When using the `Update-to-use-LTI-Advantage` branch of the code, one cannot delete a course `deployment id`  - it throws an `Exception - Class 'enrol_lti_plugin' not found` error

**Comment by ajuszczyk** [comment]
Could not replicate. Could you describe the steps to reproduce, please? Could you also provide moodle and lugin versions used, please?

**Comment by perllaghu** [comment]
I will send you a link to a demonstration service....
